apiVersion: v1
kind: Namespace
metadata:
  name: velero
  "labels": {
    "name": "development"
  }
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: velero
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: velero
spec:
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
      
#kubectl apply -f nginx-2-node-deployment.yaml
#kubectl expose deployment nginx-deployment --name nginx-service --namespace velero --port=80 --target-port=80
#kubectl proxy &
#curl http://localhost:8001/api/v1/namespaces/velero/services/http:nginx-dev-http:/proxy/
